baseURL = "https://tohomeassistant.gr/"
languageCode = "gr-el"
title = "Arcana for Hugo"
theme = "arcana"
copyright = "© ToHomeAssistant. All rights reserved"

[taxonomies]
    tag = "tags"

[params]
    description = "A business/corporate style responsive site template."
    show_post_dates = false

    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/groups/472308593754940"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/drthanwho/tohomeassistant.gr"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"

    [params.footer]

        [[params.footer.links]]
            header = "Χρήσιμοι Σύνδεσμοι"
        [[params.footer.links.links]]
            title = "Mattis et quis rutrum"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse amet varius"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan dolor"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis rutrum accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Suspendisse varius nibh"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus mattis"
            url = "#"

        [[params.footer.links]]
            header = "Διαβάσετε Επίσης"
        [[params.footer.links.links]]
            title = "Duis neque nisi dapibus"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum accumsan sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Mattis et sed accumsan"
            url = "#"
        [[params.footer.links.links]]
            title = "Duis neque nisi sed"
            url = "#"
        [[params.footer.links.links]]
            title = "Sed et dapibus quis"
            url = "#"
        [[params.footer.links.links]]
            title = "Rutrum amet varius"
            url = "#"

        [params.footer.contact_form]
            enabled = true
            header = "Επικοινωνήστε μαζί μας!"
            action = ""
