baseURL = "https://tohomeassistant.gr/"
languageCode = "gr-el"
title = "Arcana for Hugo"
theme = "arcana"
copyright = "© ToHomeAssistant. All rights reserved"
[taxonomies]
    tag = "tags"

[params]
    show_post_dates = true
    googleTagManagerID = "GTM-K7PSQBF"

    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/groups/472308593754940"
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "https://github.com/drthanwho/tohomeassistant.gr"
    [[params.social]]
        title = "Creative Commons"
        icon = "fa-creative-commons"
        url = "https://creativecommons.org/"

    [params.footer]

        [[params.footer.links]]
            header = "Χρήσιμοι Σύνδεσμοι"
        [[params.footer.links.links]]
            title = "Home Assistant Blog"
            url = "https://www.home-assistant.io/blog/"
        [[params.footer.links.links]]
            title = "ESPHOME"
            url = "https://esphome.io/"
        [[params.footer.links.links]]
            title = "Tasmota"
            url = "https://tasmota.github.io/docs/"
        [[params.footer.links.links]]
            title = "WLED"
            url = "https://kno.wled.ge/"
        [[params.footer.links]]
            header = "Διαβάσετε Επίσης"
