[[main]]
    name = "Home Assistant"
    weight = 20
[[main]]
    parent = "Home Assistant"
    name = "Τα Βασικά"
    url = "/home-assistant/τα-βασικα/"
    weight = 30
[[main]]
    parent = "Home Assistant"
    name = "Μέθοδοι Εγκατάστασης"
    url = "/home-assistant/μέθοδοι-εγκατάστασης/"
    weight = 40
[[main]]
    parent = "Home Assistant"
    name = "Αυτοματισμοί"
    url = "/home-assistant/αυτοματισμοί/"
    weight = 50
[[main]]
    name = "Integrations"
    weight = 70
    url = "/integrations/"
[[main]]
    name = "DIY"
    weight = 80
    url = "/diy/"
