[[main]]
    name = "Home Assistant"
    weight = 20
[[main]]
    parent = "Home Assistant"
    name = "Τα Βασικά"
    url = "/posts/home-assistant/τα-βασικά/"
    weight = 30
[[main]]
    parent = "Home Assistant"
    name = "Μέθοδοι Εγκατάστασης"
    url = "/posts/home-assistant/μέθοδοι-εγκατάστασης/"
    weight = 40
[[main]]
    parent = "Home Assistant"
    name = "Αυτοματισμοί"
    url = "/posts/home-assistant/αυτοματισμοί/"
    weight = 50
[[main]]
    name = "Integrations"
    weight = 60
    url = "/posts/integrations/"
[[main]]
    name = "DIY"
    weight = 70
    url = "/posts/diy/"
