name: Deploy to Cloudflare Workers with Wrangler
uses: cloudflare/wrangler-action@2.0.0

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <main|preview>"
        required: true
        default: "preview"
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
